<?php

namespace frontend\controllers;

use frontend\models\Categories;
use frontend\models\ExecutorCategories;
use frontend\models\Files;
use frontend\models\SettingsForm;
use frontend\models\Tasks;
use frontend\models\Users;
use frontend\models\WorkPhotos;
use frontend\services\SettingsFormService;
use Yii;
use yii\base\Exception;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use yii\web\UploadedFile;

class SettingsController extends SecuredController
{

    public function beforeAction($action)
    {
        if ($this->action->id == 'index') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        $categories = Categories::find()->all();
        $user_id = Yii::$app->user->id;
        $settings = new SettingsForm();
        $user = Users::findOne($user_id);
        $settings->setAttributes($user->attributes);
        $settings->password = NULL;

       if ($files = UploadedFile::getInstancesByName('file')) {
           SettingsFormService::savePhotos($files);
       }

        if (Yii::$app->request->post()) {
            $settings->load(Yii::$app->request->post());
            (new SettingsFormService())->execute($settings, $user, $categories);
            $this->redirect(['settings/index']);
        }
        return $this->render('index', ['model' => $settings, 'categories' => $categories, 'user_id' => $user_id, 'user' => $user]);
    }
}
