<?php

namespace taskforce\app;

use frontend\models\Notifications;

class EventWidget extends \yii\base\Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run() {
        $events = Notifications::find()->where(['recipient_id' => \Yii::$app->user->getId()])->andWhere(['read' => Notifications::UNREAD])->all();

        return $this->render('events', ['events' => $events]);
    }
}
