<?php

namespace taskforce\app;

use frontend\models\Notifications;
use yii\helpers\Html;

class newMessageWidget extends \yii\base\Widget
{
     public $task_id;

    protected $messages;

     public function init()
     {
         parent::init();// TODO: Change the autogenerated stub
         $this->messages = Notifications::find()->where(['task_id' => $this->task_id])
             ->andWhere(['type' => 'message'])->andWhere(['recipient_id' => \Yii::$app->user->id])
             ->andWhere(['read' => Notifications::UNREAD])->count();
     }

     public function run()
     {
         parent::run(); // TODO: Change the autogenerated stub
         if($this->messages) {
             return Html::a('<b>' . $this->messages . '</b>', ['tasks/view', 'id' => $this->task_id],
             ['class' => 'my-list__bottom-chat  my-list__bottom-chat--new']);
         } else {
             return Html::a(' ', ['tasks/view', 'id' => $this->task_id], ['class' => 'my-list__bottom-chat']);
         }
     }
}
